version: "3.1"

services:
  reverse_proxy:
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:80
    networks:
      - frontend-network

  frontend:
    build:
      context: archivio-digitale-client
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app/node_modules
      - ./archivio-digitale-client:/app
    ports:
      - 4001:8080
    depends_on:
      - backend
    networks:
      - frontend-network

  backend:
    build:
      context: archivio-digitale-server
      dockerfile: docker/Dockerfile
    restart: always
    secrets:
      - archivio_server_jwt_secret
    environment:
      MONGODB_URI: "mongodb://database:27017/archivio"
      MAILER_URL: "http://mailer/send"
      JWT_SECRET_FILE: "/run/secrets/archivio_server_jwt_secret"
    volumes:
      - /app/node_modules
      - ./archivio-digitale-server:/app
      - server-data:/app/server/public
    ports:
      - 4002:3000
    depends_on:
      - database
    networks:
      - backend-network
      - frontend-network

  database:
    image: mongo:3.4.19-jessie
    restart: always
    volumes:
      - database-data:/data/db
      - database-config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: archivio
    networks:
      - backend-network
      
  mailer:
    build:
      context: archivio-digitale-mailer
      dockerfile: docker/Dockerfile
    restart: always
    secrets:
      - archivio_mailer_user
      - archivio_mailer_password
    volumes:
      - /app/node_modules
      - ./archivio-digitale-mailer:/app
    environment:
      - USER_FILE=/run/secrets/archivio_mailer_user
      - PASSWORD_FILE=/run/secrets/archivio_mailer_password
      - SERVER=smtp.ionos.com
      - FROM=me@riccardosangiorgio.com
    networks:
      - backend-network

secrets:
  archivio_server_jwt_secret:
    file: jwt_secret.txt
  archivio_mailer_user:
    file: mailer_user.txt
  archivio_mailer_password:
    file: mailer_password.txt

networks:
  frontend-network:
  backend-network:

volumes:
  database-data:
  database-config:
  server-data:
