FROM nginx:latest
COPY default.conf.dev.template /etc/nginx/conf.d/default.conf.dev.template

ENV PORT=80 \
  CLIENT=frontend \
  CLIENT_PORT=8080 \
  API=backend \
  API_PORT=3000

EXPOSE 80

CMD /bin/bash -c "envsubst '\$PORT \$CLIENT \$CLIENT_PORT \$API \$API_PORT' < /etc/nginx/conf.d/default.conf.dev.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
